export const SET_SKILLS = 'SET_SKILLS'
export const ADD_SKILL = 'ADD_SKILL'
export const SKILL_UPDATED = 'SKILL_UPDATED'
export const SKILL_FETCHED = 'SKILL_FETCHED'
export const SKILL_DELETED = 'SKILL_DELETED'
export const SKILL_COUNT = 'SKILL_COUNT'


export const SET_EMPLOYEES = 'SET_EMPLOYEES'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED'
export const EMPLOYEE_FETCHED = 'EMPLOYEE_FETCHED'
export const EMPLOYEE_DELETED = 'EMPLOYEE_DELETED'
export const EMPLOYEE_COUNT = 'EMPLOYEE_COUNT'
